"""
Assignment 2 - Kafka Producer
Streams the sample data generated by generate_sample_data.py into the Kafka
topics defined in Assignment 1's pipeline design:

    Topic 1: user_static_master     (partition key = user_id, even/odd)
    Topic 2: ride_requests          (partition key = batch, A/B)
    Topic 3: driver_location_feed   (partition key = zone_cluster, A/B)

Run:
    pip install kafka-python
    python3 producer.py
"""

import json
import time
from kafka import KafkaProducer

BOOTSTRAP_SERVERS = ["localhost:9092"]   # change if your broker is elsewhere

producer = KafkaProducer(
    bootstrap_servers=BOOTSTRAP_SERVERS,
    value_serializer=lambda v: json.dumps(v).encode("utf-8"),
    key_serializer=lambda k: str(k).encode("utf-8") if k is not None else None,
)


def stream_file(filepath, topic, key_field, delay=0.5):
    """Load a JSON array from filepath and send each record to `topic`,
    using record[key_field] as the Kafka message key (drives partitioning)."""
    with open(filepath, "r") as f:
        records = json.load(f)

    print(f"\n>>> Streaming {len(records)} records to topic '{topic}' ...")
    for i, record in enumerate(records, start=1):
        key = record.get(key_field)
        future = producer.send(topic, key=key, value=record)
        try:
            metadata = future.get(timeout=10)
            print(f"[{topic}] #{i} sent -> partition={metadata.partition}, "
                  f"offset={metadata.offset}, key={key}")
        except Exception as e:
            print(f"[{topic}] #{i} FAILED: {e}")
        time.sleep(delay)  # simulate real-time streaming pace

    producer.flush()
    print(f">>> Finished streaming to '{topic}'.")


if __name__ == "__main__":
    # Topic 1: static baseline data (partitioned by even/odd user_id)
    stream_file("data/user_static_master.json", "user_static_master",
                key_field="user_id", delay=0.3)

    # Topic 2: live ride requests (partitioned by batch A/B)
    stream_file("data/ride_requests.json", "ride_requests",
                key_field="batch", delay=0.5)

    # Topic 3: live driver GPS pings (partitioned by zone_cluster A/B)
    stream_file("data/driver_location_feed.json", "driver_location_feed",
                key_field="zone_cluster", delay=0.3)

    print("\nAll sample data streamed successfully.")
    producer.close()
